tieto_lifecycle_management_notifications.settings:
  type: mapping
  mapping:
    disabled:
      type: boolean
      label: 'Disabled'
    from_mail:
      type: string
      label: 'From mail'
    contact_mail:
      type: string
      label: 'Contact mail'
    fallback_recipients:
      type: sequence
      label: 'Fallback recipient mails'
      sequence:
        type: string
        label: 'Email'
